"""extend db schema

Revision ID: ec13274308ba
Revises: 4018f8258056
Create Date: 2017-03-21 19:17:34.590344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec13274308ba'
down_revision = '4018f8258056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('deadline', sa.DATE(), nullable=True),
    sa.Column('text', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
